[project]
name = "impluse"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "logging>=0.4.9.6",
    "matplotlib>=3.10.8",
    "mplfinance>=0.12.10b0",
    "numpy>=2.4.1",
    "pandas>=2.3.3",
    "polars>=1.37.0",
    "pyarrow>=22.0.0",
    "pytest>=9.0.2",
    "yfinance>=1.0",
]
